baseURL = "/"
languageCode = "en-us"
title = "Mark Walker"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Mark Walker - All rights reserved"
enableEmoji = true
publishDir = "public"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
logo = "/icons/dove.png"
description = "TODO Punchline"
featuredvideo = "https://www.youtube.com/embed/lOh8MlYkv_0"

#mailchimp = "you can provide a mailchimp-link here"

[params.author]
name = "Mark Walker"
thumbnail = "/images/author.JPG"
description = ""

[params.index]
picture = "/images/bateman.png"
title = "Mark walker"
subtitle = "Welcome to my blog!"
mdtext = '''
Soon you will find some epic shit here!\
### There will be the links for sub pages
'''
alertbar = false

[params.social]
twitter = "<username>"
youtube = "<username>"
## Main Menu
[[menu.main]]
name = "About Me"
identifier = "about"
weight = 200
url = "/static/about"
[[menu.main]]
name = "Essays"
identifier = "essays"
weight = 200
url = "/essays"
[[menu.main]]
name = "Blog"
weight = 100
identifier = "blog"
url = "/blog"

